### PR TITLE
Create Github Gradle Workflow

### PR DESCRIPTION
**Pull request by kevindavee**
Build and Run test CI

Resolves: #27

### CODE REVIEW

**Comment by kevindavee** [comment]
What do you think about the Java versions we are testing against? Is it too much? @stanleynguyen @tohyongcheng @javiersuweijie

**Comment by kevindavee** [comment]
This command only build the code and test it. There's no publishing activity

**Comment by stanleynguyen** [comment]
@kevindavee Oh cool. I just realised the BINTRAY vars are just so that the build won't fail.
Is there a way we can run the test without setting these vars?

**Comment by kevindavee** [comment]
Let me remove it and see if it is working or not.

**Pull request merged**
